Repository pagers-org/react-world, pull requests merged in 2023-09, with the labels that each got.

#56 chore: 프로젝트 세팅 부족한 부분 추가합니다.
  .gitattributes
  .github/workflows/playwright.yml
  .gitignore
  package.json
  playwright.config.ts
  pnpm-lock.yaml
  postcss.config.js
  public/assets/favicon.ico
  public/assets/logo.png
  public/styles/ionicons.min.css
  public/styles/main.css
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.module.css
  src/app/page.tsx
  src/constants/temp
  tailwind.config.ts
  tests-examples/demo-todo-app.spec.ts
  tests/example.spec.ts
  webpack.config.js
Labels: chore

#43 feat(home): index.html 템플릿 기반으로 홈페이지를 만듭니다.
  apps/react-world/src/App.css
  apps/react-world/src/App.tsx
  apps/react-world/src/index.css
  apps/react-world/src/main.tsx
  apps/react-world/src/pages/home.tsx
  apps/react-world/styles/ionicons.min.css
  apps/react-world/styles/main.css
  templates/index.html
Labels: feature

#44 feat(app, login): login.html 베이스로 로그인 페이지를 만들고, 홈/로그인 간 페이지 전환이 가능하도록 합니다.
  .pnp.cjs
  .yarn/cache/@remix-run-router-npm-1.8.0-a97098c5e8-f754f02d3b.zip
  .yarn/cache/react-router-dom-npm-6.15.0-69f6e8fcf2-95301837e2.zip
  .yarn/cache/react-router-npm-6.15.0-e561018c7a-345b29277e.zip
  apps/react-world/package.json
  apps/react-world/src/main.tsx
  apps/react-world/src/pages/login.tsx
  apps/react-world/src/routes/Routes.tsx
  apps/react-world/src/routes/index.ts
  templates/login.html
  yarn.lock
Labels: feature, chore

#45 feat(app, register): register.html 템플릿 기반으로 회원가입 페이지를 만들고, 페이지 라우팅을 추가합니다.
  apps/react-world/src/pages/register.tsx
  apps/react-world/src/routes/Routes.tsx
  templates/register.html
Labels: feature

#46 feat(app, article): article.html 템플릿 기반으로 아티클 페이지를 만들고, 페이지 라우팅을 추가합니다.
  apps/react-world/src/pages/article.tsx
  apps/react-world/src/routes/Routes.tsx
  templates/article.html
Labels: feature

#51 feat(app, editor): edit.html 템플릿 기반으로 아티클 작성/수정 페이지를 만들고, 페이지 라우팅을 추가합니다.
  apps/react-world/src/pages/editor.tsx
  apps/react-world/src/routes/Routes.tsx
  templates/edit.html
Labels: feature

#52 feat(app, settings): settings.html 템플릿 기반으로 설정화면 페이지를 만들고, 페이지 라우팅을 추가합니다.
  apps/react-world/src/pages/settings.tsx
  apps/react-world/src/routes/Routes.tsx
  templates/settings.html
Labels: feature

#53 feat(app, profile): profile.html 템플릿 기반으로 프로필 페이지를 만들고, 페이지 라우팅을 추가합니다.
  apps/react-world/src/pages/profile.tsx
  apps/react-world/src/routes/Routes.tsx
  templates/profile.html
Labels: feature

#54 chore: 프로젝트 기초 환경 설정을 완료합니다.
  .eslintrc.json
  .gitignore
  libs/vite-react-component/.eslintrc.cjs
  libs/vite-react-component/.gitignore
  libs/vite-react-component/.gitkeep
  libs/vite-react-component/README.md
  libs/vite-react-component/index.html
  libs/vite-react-component/package.json
  libs/vite-react-component/src/buttons/Button.tsx
  libs/vite-react-component/src/buttons/index.ts
  libs/vite-react-component/src/index.ts
  libs/vite-react-component/src/main.tsx
  libs/vite-react-component/src/vite-env.d.ts
  libs/vite-react-component/tsconfig.json
  libs/vite-react-component/tsconfig.node.json
  libs/vite-react-component/vite.config.ts
  package-lock.json
  package.json
  packages/next13/.eslintrc.json
  packages/next13/.gitkeep
  packages/next13/app/layout.tsx
  packages/next13/app/page.tsx
  packages/next13/next-env.d.ts
  packages/next13/next.config.js
  packages/next13/package.json
  packages/next13/tsconfig.json
Labels: chore

#59 feat(register): 회원가입 페이지에서 새로 회원가입을 할 수 있는 기능을 구현합니다.
  .pnp.cjs
  .vscode/settings.json
  .yarn/cache/@types-axios-npm-0.14.0-42f41917ea-12a230b940.zip
  .yarn/cache/asynckit-npm-0.4.0-c718858525-7b78c451df.zip
  .yarn/cache/axios-npm-1.5.0-35a845e191-e7405a5dbb.zip
  .yarn/cache/broadcast-channel-npm-3.7.0-81ceba70bb-803794c48d.zip
  .yarn/cache/combined-stream-npm-1.0.8-dc14d4a63a-49fa4aeb49.zip
  .yarn/cache/delayed-stream-npm-1.0.0-c5a4c4cc02-46fe6e83e2.zip
  .yarn/cache/detect-node-npm-2.1.0-e8de0e94f7-832184ec45.zip
  .yarn/cache/follow-redirects-npm-1.15.2-1ec1dd82be-faa66059b6.zip
  .yarn/cache/form-data-npm-4.0.0-916facec2d-01135bf867.zip
  .yarn/cache/js-sha3-npm-0.8.0-decf3ddcfa-75df77c1fc.zip
  .yarn/cache/match-sorter-npm-6.3.1-ff3565ebb9-a4b02b676a.zip
  .yarn/cache/microseconds-npm-0.2.0-dbdb8ab8bb-22bfa8553f.zip
  .yarn/cache/mime-db-npm-1.52.0-b5371d6fd2-0d99a03585.zip
  .yarn/cache/mime-types-npm-2.1.35-dd9ea9f3e2-89a5b7f1de.zip
  .yarn/cache/nano-time-npm-1.0.0-6eca938be8-eef8548546.zip
  .yarn/cache/oblivious-set-npm-1.0.0-8e7336b241-f31740ea9c.zip
  .yarn/cache/proxy-from-env-npm-1.1.0-c13d07f26b-ed7fcc2ba0.zip
  .yarn/cache/react-query-npm-3.39.3-72b2a93edf-d2de6a0992.zip
  .yarn/cache/remove-accents-npm-0.4.2-7cb341092a-84a6988555.zip
  .yarn/cache/unload-npm-2.2.0-c40df6b4d0-88ba950c5f.zip
  .yarn/cache/use-sync-external-store-npm-1.2.0-44f75d2564-5c639e0f8d.zip
  .yarn/cache/zustand-npm-4.4.1-f6868a7326-80acd0fbf6.zip
  apps/react-world/package.json
  apps/react-world/src/apis/ApiConstants.ts
  apps/react-world/src/apis/register/RegisterService.ts
  apps/react-world/src/apis/register/RegisterService.types.ts
  apps/react-world/src/hooks/useRegister.ts
  apps/react-world/src/pages/register.tsx
  apps/react-world/vite.config.ts
  yarn.lock
Labels: feature, chore

#76 chore: dependency의 위치를 수정합니다.
  package.json
  pnpm-lock.yaml
Labels: chore

#72 기본 프로젝트 세팅 (#1)
  .eslintrc.json
  .github/workflows/review-assign-action.yml
  .gitignore
  next-env.d.ts
  next.config.js
  package.json
  public/next.svg
  public/vercel.svg
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/page.tsx
  src/styles/globals.css
  src/styles/ionicons.min.css
  src/styles/main.css
  templates/article.html
  templates/edit.html
  templates/index.html
  templates/login.html
  templates/profile.html
  templates/register.html
  templates/settings.html
  tsconfig.json
  yarn.lock
Labels: chore

#74 feat(app, home): 홈페이지 내부를 React 컴포넌트로 분리하고, 공용 레이아웃으로 감싸도록 페이지 내부를 리팩토링합니다.
  .eslintrc.js
  apps/react-world/src/components/Footer.tsx
  apps/react-world/src/components/Layout.tsx
  apps/react-world/src/components/NavBar.tsx
  apps/react-world/src/components/home/ArticlePreview.tsx
  apps/react-world/src/components/home/ArticleTagList.tsx
  apps/react-world/src/components/home/HomeBanner.tsx
  apps/react-world/src/components/home/HomeFeedContents.tsx
  apps/react-world/src/components/home/HomeFeedTab.tsx
  apps/react-world/src/components/home/HomePageContainer.tsx
  apps/react-world/src/components/home/Pagination.tsx
  apps/react-world/src/pages/home.tsx
  apps/react-world/src/routes/Routes.tsx
Labels: feature, chore

#77 feat(app, home): emotion 기반으로 홈 배너와 홈 페이지 컨테이너 로직을 변경합니다.
  .pnp.cjs
  .yarn/cache/@babel-helper-module-imports-npm-7.22.15-687e77ee50-ecd7e457df.zip
  .yarn/cache/@babel-helper-validator-identifier-npm-7.22.15-d99c246e11-eb0bee4bda.zip
  .yarn/cache/@babel-runtime-npm-7.22.15-b21c55a700-793296df1e.zip
  .yarn/cache/@babel-types-npm-7.22.15-17bb06ecf6-a2aa59746d.zip
  .yarn/cache/@emotion-babel-plugin-npm-11.11.0-c1dcc4c884-6b363edccc.zip
  .yarn/cache/@emotion-cache-npm-11.11.0-3e6e449071-8eb1dc22be.zip
  .yarn/cache/@emotion-hash-npm-0.9.1-650576c2b1-716e17e48b.zip
  .yarn/cache/@emotion-is-prop-valid-npm-1.2.1-794afe6a94-8f42dc573a.zip
  .yarn/cache/@emotion-memoize-npm-0.8.1-9b1e35ff15-a19cc01a29.zip
  .yarn/cache/@emotion-react-npm-11.11.1-a07d6a6ebd-aec3c36650.zip
  .yarn/cache/@emotion-serialize-npm-1.1.2-4b856d3761-413c352e65.zip
  .yarn/cache/@emotion-sheet-npm-1.2.2-a918ac483c-d973273c9c.zip
  .yarn/cache/@emotion-styled-npm-11.11.0-9a95c8527d-904f641aad.zip
  .yarn/cache/@emotion-unitless-npm-0.8.1-bcf0a8f565-385e21d184.zip
  .yarn/cache/@emotion-use-insertion-effect-with-fallbacks-npm-1.0.1-730758c66c-700b6e5bbb.zip
  .yarn/cache/@emotion-utils-npm-1.2.1-3d04f99348-e0b44be070.zip
  .yarn/cache/@emotion-weak-memoize-npm-0.3.1-bfc18213af-b2be47caa2.zip
  .yarn/cache/@types-parse-json-npm-4.0.0-298522afa6-fd6bce2b67.zip
  .yarn/cache/babel-plugin-macros-npm-3.1.0-320e781f4e-765de4abeb.zip
  .yarn/cache/cosmiconfig-npm-7.1.0-13a5090bcd-c53bf7befc.zip
  .yarn/cache/error-ex-npm-1.3.2-5654f80c0f-c1c2b8b65f.zip
  .yarn/cache/find-root-npm-1.1.0-a16a94005f-b2a59fe4b6.zip
  .yarn/cache/hoist-non-react-statics-npm-3.3.2-e7b709e6c1-b153827042.zip
  .yarn/cache/is-arrayish-npm-0.2.1-23927dfb15-eef4417e3c.zip
  .yarn/cache/json-parse-even-better-errors-npm-2.3.1-144d62256e-798ed4cf33.zip
  .yarn/cache/lines-and-columns-npm-1.2.4-d6c7cc5799-0c37f9f7fa.zip
  .yarn/cache/parse-json-npm-5.2.0-00a63b1199-62085b17d6.zip
  .yarn/cache/resolve-npm-1.22.4-faa4f32bdd-23f25174c2.zip
  .yarn/cache/resolve-patch-efbbaf0edd-c45f2545fd.zip
  .yarn/cache/source-map-npm-0.5.7-7c3f035429-5dc2043b93.zip
  .yarn/cache/stylis-npm-4.2.0-6b07f11c99-0eb6cc1b86.zip
  .yarn/cache/yaml-npm-1.10.2-0e780aebdf-ce4ada136e.zip
  apps/react-world/package.json
  apps/react-world/src/components/Layout.tsx
  apps/react-world/src/components/home/HomeBanner.styled.ts
  apps/react-world/src/components/home/HomeBanner.tsx
  apps/react-world/src/components/home/HomePageContainer.tsx
  apps/react-world/src/components/shared/Container.tsx
  apps/react-world/src/components/shared/banner/Banner.styled.ts
  apps/react-world/src/components/shared/layout/Footer.tsx
  apps/react-world/src/components/shared/layout/Layout.tsx
  apps/react-world/src/components/shared/layout/NavBar.tsx
  apps/react-world/src/components/shared/layout/index.ts
  apps/react-world/src/routes/Routes.tsx
  apps/react-world/styles/main.css
  yarn.lock
Labels: feature, chore

#78 feat(app): emotion 기반으로 공용 네비바 로직을 변경합니다.
  apps/react-world/src/components/Footer.tsx
  apps/react-world/src/components/Layout.tsx
  apps/react-world/src/components/home/HomeBanner.styled.ts
  apps/react-world/src/components/shared/layout/Layout.tsx
  apps/react-world/src/components/shared/layout/NavBar.tsx
  apps/react-world/src/components/shared/layout/NavBar/NavBar.tsx
  apps/react-world/src/components/shared/layout/NavBar/NavBarBrand.tsx
  apps/react-world/src/components/shared/layout/NavBar/NavItem.tsx
  apps/react-world/src/components/shared/layout/NavBar/NavList.tsx
  apps/react-world/src/routes/Routes.tsx
  apps/react-world/styles/main.css
Labels: feature, status: needs-healing

#79 feat(app): 앱에 필요한 폰트들을 일부 추가하고, 전역 스타일링 설정을 추가합니다.
  apps/react-world/public/assets/favicon.ico
  apps/react-world/public/assets/logo.png
  apps/react-world/public/assets/vite.svg
  apps/react-world/public/fonts/SourceSansPro/SourceSansPro-Bold.otf
  apps/react-world/public/fonts/SourceSansPro/SourceSansPro-Light.otf
  apps/react-world/public/fonts/SourceSansPro/SourceSansPro-Regular.otf
  apps/react-world/public/fonts/SourceSansPro/SourceSansPro-Semibold.otf
  apps/react-world/public/fonts/TitilliumWeb/TitilliumWeb-Bold.ttf
  apps/react-world/public/fonts/TitilliumWeb/TitilliumWeb-Regular.ttf
  apps/react-world/public/fonts/TitilliumWeb/TitilliumWeb-SemiBold.ttf
  apps/react-world/src/assets/react.svg
  apps/react-world/src/routes/Routes.tsx
  apps/react-world/styles/globalStyles.tsx
Labels: feature, status: dependent, status: needs-healing

#83 fix(app): 프로젝트 내에서 React.FC 를 안 쓰도록 리팩토링합니다.
  apps/react-world/src/components/Footer.tsx
  apps/react-world/src/components/home/ArticlePreview.tsx
  apps/react-world/src/components/home/ArticleTagList.tsx
  apps/react-world/src/components/home/HomeBanner.tsx
  apps/react-world/src/components/home/HomeFeedContents.tsx
  apps/react-world/src/components/home/HomeFeedTab.tsx
  apps/react-world/src/components/home/Pagination.tsx
  apps/react-world/src/components/shared/layout/Footer.tsx
  apps/react-world/src/components/shared/layout/NavBar/NavBar.tsx
  apps/react-world/src/components/shared/layout/NavBar/NavItem.tsx
  apps/react-world/src/pages/register.tsx
Labels: improvement

#84 feat(app): emotion 기반으로 공용 푸터 로직을 변경합니다.
  apps/react-world/src/components/Footer.tsx
  apps/react-world/src/components/Layout.tsx
  apps/react-world/src/components/shared/layout/Footer.styled.ts
  apps/react-world/src/components/shared/layout/Footer.tsx
  apps/react-world/styles/main.css
Labels: improvement, status: needs-healing

#88 refactor(app): API Path 를 선언하는 방식을 개선합니다.
  apps/react-world/src/apis/ApiConstants.ts
  apps/react-world/src/apis/apiInstances.ts
  apps/react-world/src/apis/register/RegisterService.ts
Labels: improvement, refactor

#95 refactor(home): 홈페이지 내부 컴포넌트를 styled component 기반으로 리팩토링합니다.
  apps/react-world/src/components/home/HomeFeedTab.tsx
  apps/react-world/src/components/home/HomeFeedTabItem.tsx
  apps/react-world/src/components/home/HomePageContainer.tsx
  apps/react-world/src/components/home/Pagination.styled.ts
  apps/react-world/src/components/home/Pagination.tsx
  apps/react-world/src/components/shared/layout/NavBar/NavItem.tsx
  apps/react-world/styles/main.css
Labels: improvement, refactor

#96 refactor(home): 홈 페이지의 인기 아티클 태그를 styled component 기반으로 리팩토링합니다.
  apps/react-world/src/components/home/ArticleTagList.tsx
  apps/react-world/src/components/home/HomeFeedContents.tsx
  apps/react-world/src/components/home/HomePageContainer.tsx
  apps/react-world/src/components/home/PopularArticleTagList.styled.ts
  apps/react-world/src/components/home/PopularArticleTagList.tsx
  apps/react-world/src/components/shared/Col.styled.ts
Labels: status: needs-healing, refactor

#100 refactor(home): 홈 페이지의 아티클 프리뷰 컴포넌트를 styled component 기반으로 리팩토링합니다.
  apps/react-world/src/apis/article/ArticlePreviewService.types.ts
  apps/react-world/src/components/home/ArticlePreview.styled.ts
  apps/react-world/src/components/home/ArticlePreview.tsx
  apps/react-world/src/components/home/HomeFeedContents.tsx
Labels: improvement, refactor

#103 feat(home): 홈 페이지에서 실제 아티클 프리뷰 데이터를 불러와 표시하도록 합니다.
  .pnp.cjs
  .yarn/cache/@tanstack-query-core-npm-4.35.3-8d75c7bf5e-0184cd19a2.zip
  .yarn/cache/@tanstack-react-query-npm-4.35.3-d720e9c932-4d7e4e6a84.zip
  .yarn/cache/broadcast-channel-npm-3.7.0-81ceba70bb-803794c48d.zip
  .yarn/cache/detect-node-npm-2.1.0-e8de0e94f7-832184ec45.zip
  .yarn/cache/js-sha3-npm-0.8.0-decf3ddcfa-75df77c1fc.zip
  .yarn/cache/match-sorter-npm-6.3.1-ff3565ebb9-a4b02b676a.zip
  .yarn/cache/microseconds-npm-0.2.0-dbdb8ab8bb-22bfa8553f.zip
  .yarn/cache/nano-time-npm-1.0.0-6eca938be8-eef8548546.zip
  .yarn/cache/oblivious-set-npm-1.0.0-8e7336b241-f31740ea9c.zip
  .yarn/cache/react-query-npm-3.39.3-72b2a93edf-d2de6a0992.zip
  .yarn/cache/remove-accents-npm-0.4.2-7cb341092a-84a6988555.zip
  .yarn/cache/unload-npm-2.2.0-c40df6b4d0-88ba950c5f.zip
  apps/react-world/package.json
  apps/react-world/src/apis/article/ArticlePreviewService.ts
  apps/react-world/src/apis/article/ArticlePreviewService.types.ts
  apps/react-world/src/components/home/ArticlePreview.tsx
  apps/react-world/src/components/home/HomeFeedContents.tsx
  apps/react-world/src/main.tsx
  apps/react-world/src/quries/useArticlePreviewQuery.ts
  yarn.lock
Labels: feature

#92 feat: User/Auth 구현
  .eslintignore
  .eslintrc.json
  .gitattributes
  .github/ISSUE_TEMPLATE/task.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/playwright.yml
  .gitignore
  .husky/pre-commit
  .prettierrc
  jest.config.js
  jest.setup.ts
  next.config.js
  package.json
  playwright.config.ts
  pnpm-lock.yaml
  postcss.config.js
  public/favicon.ico
  src/TestComponentForTest.tsx
  src/__Test__.test.tsx
  src/api/users.ts
  src/app/article/[article_title]/page.tsx
  src/app/editor/page.tsx
  src/app/fonts.ts
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/profile/[username]/page.tsx
  src/app/register/page.tsx
  src/app/settings/page.tsx
  src/composables/Footer/index.tsx
  src/composables/Nav/index.tsx
  src/constants/api.ts
  src/constants/env.ts
  src/constants/key.ts
  src/constants/time.ts
  src/global.d.ts
  src/hooks/temp
  src/pageComponents/HomePageMain.tsx
  src/pageComponents/article/[article_title]/ArticleDetailPageMain.tsx
  src/pageComponents/editor/EditorPageMain.tsx
  src/pageComponents/login/LoginPageMain.tsx
  src/pageComponents/profile/[username]/ProfileUserPageMain.tsx
  src/pageComponents/register/RegisterPageMain.tsx
  src/pageComponents/settings/SettingsPageMain.tsx
  src/stores/users.ts
  src/styles/globals.css
  src/tests/temp
  src/types/api/users.ts
  src/utils/cookie.ts
  tailwind.config.ts
  templates/index.html
  templates/styles/ionicons.min.css
  templates/styles/main.css
  tests-examples/demo-todo-app.spec.ts
  tests/example.spec.ts
  tsconfig.json
  tsconfig.test.json
  webpack.config.js
  yarn.lock
Labels: feature

#115 chore(app): ReactQueryDevtools 을 셋업합니다.
  .pnp.cjs
  .yarn/cache/@tanstack-match-sorter-utils-npm-8.8.4-488b98c113-d005f50075.zip
  .yarn/cache/@tanstack-react-query-devtools-npm-4.35.3-ebc52e8940-59495f9dab.zip
  .yarn/cache/copy-anything-npm-3.0.5-562d15fb3f-d39f6601c1.zip
  .yarn/cache/is-what-npm-4.1.15-328677a458-fe27f6cd4a.zip
  .yarn/cache/remove-accents-npm-0.4.2-7cb341092a-84a6988555.zip
  .yarn/cache/superjson-npm-1.13.1-39607ca2e6-9c8c664a92.zip
  apps/react-world/package.json
  apps/react-world/src/main.tsx
  yarn.lock
Labels: chore

#110 feat(home): 홈 페이지의 Pagination 을 실제 아티클 프리뷰 데이터를 기반으로 렌더링하도록 합니다.
  apps/react-world/src/apis/article/ArticlePreviewService.ts
  apps/react-world/src/components/home/HomeFeedContents.tsx
  apps/react-world/src/components/home/Pagination.styled.ts
  apps/react-world/src/components/home/Pagination.tsx
Labels: feature

#112 feat(home): 홈 페이지의 인기 아티클 태그 목록 실제 데이터를 조회 후 연동하도록 합니다.
  apps/react-world/src/apis/article/PopularArticleTagService.ts
  apps/react-world/src/apis/article/PopularArticleTagService.types.ts
  apps/react-world/src/components/home/HomeFeedContents.tsx
  apps/react-world/src/quries/useArticlePreviewQuery.ts
  apps/react-world/src/quries/usePopularArticleTagsQuery.ts
Labels: feature

#87 chore(app): 프로젝트 초기설정 완료
  2taesung/.eslintrc.json
  2taesung/.gitignore
  2taesung/.prettierrc
  2taesung/.vscode/settings.json
  2taesung/README.md
  2taesung/next.config.js
  2taesung/package-lock.json
  2taesung/package.json
  2taesung/postcss.config.js
  2taesung/public/next.svg
  2taesung/public/vercel.svg
  2taesung/src/app/favicon.ico
  2taesung/src/app/globals.css
  2taesung/src/app/layout.tsx
  2taesung/src/app/page.tsx
  2taesung/tailwind.config.ts
  2taesung/tsconfig.json
Labels: chore

#125 feat(article): 아티클 상세 페이지를 코멘트 영역을 제외하고 실제 데이터와 연동합니다.
  apps/react-world/src/apis/apiInstances.ts
  apps/react-world/src/apis/article/Article.types.ts
  apps/react-world/src/apis/article/ArticlePreviewService.ts
  apps/react-world/src/apis/article/ArticlePreviewService.types.ts
  apps/react-world/src/apis/article/ArticleService.ts
  apps/react-world/src/apis/article/ArticleService.types.ts
  apps/react-world/src/components/article/ArticleActions.tsx
  apps/react-world/src/components/article/ArticleComments.tsx
  apps/react-world/src/components/article/ArticleContents.tsx
  apps/react-world/src/components/article/ArticleHeader.tsx
  apps/react-world/src/components/article/ArticlePageContainer.tsx
  apps/react-world/src/components/home/ArticlePreview.styled.ts
  apps/react-world/src/components/home/ArticlePreview.tsx
  apps/react-world/src/components/home/HomeFeedContents.tsx
  apps/react-world/src/main.tsx
  apps/react-world/src/pages/article.tsx
  apps/react-world/src/quries/useArticleDetailQuery.ts
  apps/react-world/src/routes/AppRoutes.tsx
  apps/react-world/src/routes/Routes.tsx
  apps/react-world/src/routes/index.ts
  apps/react-world/src/utils/dateUtils.ts
  apps/react-world/tsconfig.json
  apps/react-world/vite.config.ts
Labels: feature

#138 feat(article): 아티클 상세화면에 진입 시 실제 아티클 댓글 데이터를 받아 렌더링하도록 합니다.
  apps/react-world/src/apis/article/ArticleService.ts
  apps/react-world/src/apis/article/ArticleService.types.ts
  apps/react-world/src/components/article/ArticleComments.tsx
  apps/react-world/src/components/article/ArticlePageContainer.tsx
  apps/react-world/src/quries/useArticleCommentsQuery.ts
  apps/react-world/vite.config.ts
Labels: feature

#140 feat(app): 회원 가입 완료시 JWT 토큰을 쿠키로 저장하고 인증이 필요한 요청에 Bearer 헤더를 설정하도록 합니다.
  .pnp.cjs
  .yarn/cache/@types-js-cookie-npm-3.0.4-bd5399d847-46ac939747.zip
  .yarn/cache/js-cookie-npm-3.0.5-8fc8fcc9b4-2dbd2809c6.zip
  apps/react-world/package.json
  apps/react-world/src/apis/apiInstances.ts
  apps/react-world/src/apis/register/RegisterService.ts
  apps/react-world/src/hooks/useRegister.ts
  apps/react-world/src/utils/jwtUtils.ts
  yarn.lock
Labels: feature

#147 feat(home): 홈 페이지의 피드 타입과 페이지를 쿼리 파라미터로 설정할 수 있도록 만들고, 파라미터가 없을 때 자동으로 기본 파라미터가 지정되도록 개선합니다.
  apps/react-world/src/components/home/HomeFeedContents.tsx
  apps/react-world/src/components/home/HomeFeedTab.tsx
  apps/react-world/src/components/home/HomeFeedTabItem.tsx
  apps/react-world/src/components/home/Pagination.styled.ts
  apps/react-world/src/components/home/Pagination.tsx
  apps/react-world/src/hooks/useConditionalReplace.ts
  apps/react-world/src/hooks/useDefaultQueryParamsSetter.ts
  apps/react-world/src/pages/home.tsx
  apps/react-world/src/routes/AppRoutes.tsx
  apps/react-world/tsconfig.json
  apps/react-world/vite.config.ts
Labels: feature
